name: Analyze_my_project
on: [push]

jobs:
  buuld:
    runs-on: ubuntu-latest

    steps:
        - name: Git clone project
          uses: actions/checkout@v2

        - name: Up project
          uses: subosito/flutter-action@v1
          with:
            flutter-version: '3.19.0'

        - name: Analyze project
          run: flutter analyze